# Your personal GitHub token
github_token: 51fb61844029ee8829c17360a88a1061c21a9f9a
# Read more: https://github.com/blog/1509-personal-api-tokens
# You can generate it here: https://github.com/settings/tokens

# Guest OS timezone
timezone: Asia/Novosibirsk

# Are we need check box updates for every 'vagrant up'?
box_check_update: true

# Virtual machine name
machine_name: money-transfer

# Virtual machine IP
ip: 192.168.83.137

# Virtual machine CPU cores number
cpus: 1

# Virtual machine RAM
memory: 1024
